### ISSUE TITLE
단어 단위로 분할하는 정규표현식

### ISSUE THREAD

**Issue by hello-im-yj** [KU-NLPandAI/Deep-Learning-from-Scratch2#1]
> p.84 WARNING 네모 박스

```import re
re.split('(\W+)?',text)
```

위 정규식이 의미하는 게 무엇인지 궁금합니다. 

각 정규표현식이 뜻하는 바는
- `\W `: 문자+숫자(alphanumeric)가 아닌 문자와 매치
- `+` : 앞에 있는 문자가 최소 한 번 이상 반복되어야 매치
- `?` : 앞에 있는 문자가 없거나 하나 있을 때 매치 (있어도 되고 없어도 된다)
라고 하는데... 

(\W+) 전체를 ?로 왜 묶는지 이해가 안됩니닷...

**Comment by hello-im-yj** [comment]
코드 실행 결과도 이상하게 나와요

![image](https://user-images.githubusercontent.com/63237947/127768193-10c7ecfe-fdbc-43cf-89d8-23f58ef5bb97.png)

**Comment by Lee-Seoung-Hoon** [comment]
책의 오류인 것 같습니다. ?를 제거하고 사용하는 것이 저자가 의도하는 부분인 것 같습니다.
import re
text = 'you say goodbye.'
re.split('(\W+)',text)
