### ISSUE TITLE
page.208의 truncated BPTT의 미니배치 학습

### ISSUE THREAD

**Issue by Lee-Seoung-Hoon** [KU-NLPandAI/Deep-Learning-from-Scratch2#4]
길이가 1000인 시계열 데이터를 500개씩 끊어서 미니배치 학습을 시킨다고 표현했는데 이것을 문장이라고 생각한다면 이렇게 끊어서 학습하는 것이 올바른 언어모델의 학습방법인가요?

**Comment by Lee-Seoung-Hoon** [comment]
추가적으로 날씨데이터 같은 다른 시계열데이터의 경우에는 이렇게 끊어서 학습하는 것이 맞는 방법인가요?

**Comment by hello-im-yj** [comment]
Truncated BPTT에서는 gradient descent 현상이 나타나게 되므로 메모리를 아끼기 위해 역전파만 끊어내는 방법을 택한 것 같습니다. 
반대로 순전파는 유지되니, 이전 벡터의 hidden state 값이 다음 벡터에 반영되는 것은 문제 없이 계속된다고 봐도 될 것 같습니다 ^^
