### ISSUE TITLE
word2vec 속도 개선에 대한 의문

### ISSUE THREAD

**Issue by Lee-Seoung-Hoon** [KU-NLPandAI/Deep-Learning-from-Scratch2#6]
저자는 word2vec 속도 개선을 위해 단어의 분산 표현을 원핫 벡터를 사용하여 추출하지 않고 index값을 사용하여 단어에 대한 벡터를 추출하는 방법으로 속도를 개선하려고 하고 있습니다. 하지만 제 생각에 page.166의 방법으로 코드를 구성하였을 때 Embeddingdot 클래스의 forward의 input 값으로 idx를 받아버리면 training단계에서는 문제 없지만 inference단계에서는 idx정보가 없을 텐데 가중치에서 어느 벡터를 뽑아내야하는 지 알 수 있을까요?

**Comment by hello-im-yj** [comment]
inference 단계에서도 idx를 사용할 수 있지 않을까요? 학습 시킬 때 사용했던 corpus의 idx 를 사용하여 inference에 사용할 것 같습니다...!(만약 학습되지 않은 단어가 inference 시에 포함된다면 unknown으로 처리하는 듯 : https://jiho-ml.com/weekly-nlp-1/)
