### ISSUE TITLE
page.230에서 식5.12와 5.13

### ISSUE THREAD

**Issue by Lee-Seoung-Hoon** [KU-NLPandAI/Deep-Learning-from-Scratch2#7]
e^L이 곧 퍼플렉시티라고 저자는 표현하였고 제가 이해한 상황은 다음과 같습니다.
1. L값은 loss값이고 작을 수록 더 정답에 가깝다. 
2. e^L은 L값의 크기와 비례관계를 가진다.
3. 퍼플렉시티는 작을 수록 좋은 거다.
이를 단순히 퍼플렉시티라고 정의했다는 것에 대해서는 어떻게 이해를 하여야 할까요?

**Comment by hello-im-yj** [comment]
바로 앞페이지인 p.299에서 저자는 다음과 같이 perplexity를 '정답 확률의 역수'로 소개합니다!
저도 처음에는 이 복잡한 수식과 앞서 설명한 간단한 설명 사이에 어떤 연관이 있는지 이해하기 어려웠는데, 1장 p.41에 등장하는  cross-entropy 오차의 정의를 생각해보면 p.230의 수식 역시 동일한 의미라는 것을 알 수 있었습니다. 

<img width="184" alt="e 5-12" src="https://user-images.githubusercontent.com/63237947/131247595-b389ed82-b59a-4262-bd2c-784d412aa14b.png">

위 식에서 $t_{nk}$는 n번째 데이터의 K번째 정답레이블,  $y_{k}$는 그에 대응하는 신경망 출력(확률값)입니다. 
일단 L값에서 (-) 부호를 제외하고 생각해보면,  이는 정답 레이블(정답만 1이고 나머지는 0)의 log(확률값)을 N으로 나눠 '평균 정답 확률의 로그값'임을 알 수 있습니다. 

<img width="139" alt="e 5-13" src="https://user-images.githubusercontent.com/63237947/131247792-8f559c5e-9544-4d34-98da-93601b85b7c2.png">
그럼 이 L값을 e의 지수승으로 올리면서,  (-)가 붙은 L값은 정답 확률의 "역수"로 바뀌게 되고, 최종적으로 log와 e는 서로 상쇄되어 perplexity 자체가  '정답 확률의 역수'를 의미하게 됩니다!
